Add scoped mock documentation
mockk/mockk pull request #1175
Opened 2023-10-14 17:14 UTC by kshired

resolve #1114

2023-10-19 16:36 UTC, kshired commented
@Raibaz Can you give me some feedback of this PR?

2023-11-03 21:58 UTC, Raibaz requested changes

2023-11-03 21:58 UTC, Raibaz commented on README.md
> +### Scoped mock
Should be "Scoped mocks"

2023-11-03 21:58 UTC, Raibaz commented on README.md
> +Scoped mock is a mock that unmocks it after the block has been executed.
"A scoped mock is a mock that automatically unmocks itself after the code block passed as a parameter has been executed".

2023-11-03 21:58 UTC, Raibaz commented on README.md
> +You can use `mockkObject`, `mockkStatic` and `mockkConstructor` functions.
"You can use the `mockkObject`..."

2023-11-03 21:58 UTC, Raibaz commented on README.md
> +// ObjeBeingMocked will be reverted back after this scope.
Should be "ObjBeingMocked will be unmocked after this scope"

2023-11-04 15:37 UTC, kshired commented
@Raibaz thaks!

2023-11-04 23:00 UTC, Raibaz requested changes

2023-11-04 23:00 UTC, Raibaz commented on README.md
> +A Scoped mock is a mock that automatically unmocks itself after the code block passed as a parameter has been executed
Missing '.' at the end of the sentence.

2023-11-04 23:00 UTC, Raibaz commented on README.md
> +// Should be "ObjBeingMocked will be unmocked after this scope"
I meant the comment should be just
`// ObjBeingMocked will be unmocked after this scope` :)

2023-11-05 21:30 UTC, Raibaz approved these changes

2023-11-06 10:51 UTC, merged