Add quarkus support section
mockk/mockk pull request #783
Opened 2022-01-25 14:12 UTC by glefloch

Quarkus also support `mockk` as mock provider in the bean container. This adds the link to the library. 

Thanks for your work on this project!

2022-01-25 20:59 UTC, Raibaz requested changes

2022-01-25 20:59 UTC, Raibaz commented on README.md
> + * [quarkus-mockk](https://github.com/quarkiverse/quarkus-mockk) adds support for mocking beans in Quarkus. Documetation can be found [here](https://quarkiverse.github.io/quarkiverse-docs/quarkus-moc
There's a typo here, it should be `Documentation` :)

2022-01-25 20:59 UTC, Raibaz commented
Thanks a lot for this!

Needs a minor change then we can definitely merge it.

2022-01-26 07:22 UTC, glefloch commented
Right sorry for that. I pushed a fix.

2022-01-26 08:35 UTC, merged